# Generated by Django 4.1.2 on 2022-11-05 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                ("quantity", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
